alias ..="cd .."
alias vim="nvim"
alias serve="python -m http.server"
alias va="source venv/bin/activate"

# when yes, compile erlang with docs
# you can access erlang docs from iex
export KERL_BUILD_DOCS=yes
export EDITOR=nvim

# vim bash mode
set -o vi

source ~/.asdf/installs/fzf/0.29.0/shell/key-bindings.bash

export PATH="~/.local/bin:$PATH"

